[build]
  publish = "."
  command = "echo 'LinkedIn Expert Automation deployed!'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/"
  to = "/landing_page.html"
  status = 200

[[redirects]]
  from = "/linkedin-expert"
  to = "/landing_page.html"
  status = 200

[[redirects]]
  from = "/audit"
  to = "/landing_page.html#audit-form"
  status = 302

[context.production]
  command = "echo 'Production LinkedIn Expert deployment ready!'"

[context.deploy-preview]
  command = "echo 'Preview deployment ready!'"